from enum import Enum, unique


@unique
class Items(Enum):
    NONE = 0xFF
    RANDOM = 0xFE

    ZORLIN_SHAPE = 0x0A
    IGA_KNIFE = 0x11
    KOGA_KNIFE = 0x12
    BLOOD_SWORD = 0x17
    NAGRAROCK = 0x1F
    DEFENDER = 0x21
    SAVE_THE_QUEEN = 0x22
    EXCALIBUR = 0x23
    MASAMUNE = 0x2E
    CHIRIJIRADEN = 0x2F
    FAITH_ROD = 0x3A
    HEALING_STAFF = 0x3D
    MACE_OF_ZEUS = 0x41
    SAGE_STAFF = 0x42
    STONE_GUN = 0x49
    BLAZE_GUN = 0x4A
    GLACIER_GUN = 0x4B
    BLAST_GUN = 0x4C
    GASTRAFITIS = 0x52
    PERSEUS_BOW = 0x5B
    MADLEMGEN = 0x62
    HOLY_LANCE = 0x68
    DRAGON_WHISKER = 0x69
    WHALE_WHISKER = 0x72
    GENJI_SHIELD = 0x8C
    KAISER_PLATE = 0x8D
    VENETIAN_SHIELD = 0x8E
    GENJI_HELMET = 0x9B
    THIEF_HAT = 0xA8
    CACHUSHA = 0xA9
    BARETTE = 0xAA
    RIBBON = 0xAB
    GENJI_ARMOR = 0xB7
    RUBBER_COSTUME = 0xC7
    WHITE_ROBE = 0xCC
    ROBE_OF_LORDS = 0xCF
    CHANTAGE = 0xEC
    CHERCHE = 0xED
    SALTY_RAGE = 0xEE
    GENJI_GAUNTLET = 0xD8